version: '3'

services:
  server:
    build: .
    ports:
      - "8080:8080"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=

    # <HOSTNAME>
    container_name: postgres 
