version: '3'

services:
  server:
    build: .
    ports:
      - "3000:3000"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=hunter2
      - POSTGRES_DB=kvs

    # <HOSTNAME>
    container_name: postgres 
